### ISSUE TITLE
Add the ability to template any parameters into the zoo.cfg file

### ISSUE THREAD

**Issue by ObjectiveTruth** [sleighzy/ansible-zookeeper#39]
I'm installing zookeeper using these scripts which are great! However there are some use cases that aren't covered. For example, I'd like to add Quorum SSL however there is a limited set of variable that are templated into zoo.cfg.

To make it more generic, I propose a generic dictionary that can be passed. Jinja would then go through this dictionary and apply the `key: value` pairing into the zoo.cfg

For example, for SSLQuorum I would need the following:
```ini
        serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
        sslQuorum=true
        ssl.quorum.keyStore.location=keystore/location.p12
        ssl.quorum.keyStore.password=changeit
```

I'll make the PR but i wanted to know if you @sleighzy have any comments?
For example:

```yaml
    - role: sleighzy.zookeeper
      zookeeper_cfg_params:
        serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
        sslQuorum: true
        ssl.quorum.keyStore.location: keystore/location.p12
        ssl.quorum.keyStore.password: changeit
      become: yes
```

I'm open to the variable naming too but I think `zookeeper_cfg_params` covers it
