### ISSUE TITLE
Add a sample in readme to allow "zookeeper_servers" property from hosts list

### ISSUE THREAD

**Issue by devlibx** [sleighzy/ansible-zookeeper#42]
Hi,

This plugin was very helpful. Thanks... 

One suggestion -> I found that readme has shown how you can add "zookeeper_servers" for distributed setup. However, I think it will be easy for someone if you can add a sample like the one below (this will allow someone to have the same YAML which can work with different hosts file).
```
  roles:
    - role: sleighzy.zookeeper
      vars:
        zookeeper_servers_use_inventory_hostname: true
        zookeeper_servers: "{{ groups['zookeeper-nodes'] }}"
```

Also in the Kafka setup the following will be helpful: Most of the time the setup would need the list of ZK 
```
- role: sleighzy.kafka
      vars:        
        kafka_zookeeper_connect: "{{ groups['zookeeper-nodes'] | product([':2181']) | map('join') | list | join(',') }}"        
```
